"""Repo analysis helpers — file index extraction, scan profiles, file tree, and MCP tool implementations."""
# stdlib
import ast
import hashlib
import json
import os
import time
from datetime import date
from pathlib import Path


def _pkg():
    """Return the github_planner package module so patches applied by tests are respected."""
    import sys
    return sys.modules['extensions.gh_management.github_planner']

from terminal_hub.constants import (
    FILE_TREE_TTL,
    ANALYSIS_BATCH_SIZE,
    ANALYSIS_BATCH_SIZE_MIN,
    ANALYSIS_BATCH_SIZE_MAX,
)

# ── Caches ────────────────────────────────────────────────────────────────────
_ANALYSIS_CACHE: dict[str, dict] = {}
# Key: "owner/repo"
# {
#   "pending_md":   [{"path": str, "size": int}, ...],
#   "pending_code": [{"path": str, "size": int}, ...],
#   "analyzed":     [{"path": str, "is_markdown": bool}],
#   "skipped":      [{"path": str, "reason": str}],
#   "repo":         str,
#   "started_at":   float,
#   "last_fetched": float | None,
# }

_FILE_TREE_CACHE: dict = {}
# {
#   "tree":       dict,
#   "flat_index": list[str],
#   "fetched_at": str,
#   "root":       str,
# }

_FILE_TREE_TTL = FILE_TREE_TTL

_FILE_TREE_IGNORE = frozenset({
    ".git", "__pycache__", "venv", ".venv", "node_modules",
    ".worktrees", "worktrees", ".mypy_cache", ".pytest_cache",
    "dist", "build", "*.egg-info",
})

_MD_EXTENSIONS = {".md", ".rst", ".txt"}
_MAX_ANALYSIS_FILES = 200
_BINARY_EXTENSIONS = frozenset({
    ".png", ".jpg", ".jpeg", ".gif", ".ico", ".svg", ".webp",
    ".pdf", ".pyc", ".pyo", ".pyd", ".so", ".dll", ".exe", ".bin",
    ".pkl", ".npy", ".npz", ".db", ".sqlite", ".sqlite3",
    ".zip", ".tar", ".gz", ".bz2", ".xz", ".whl", ".egg",
    ".ttf", ".otf", ".woff", ".woff2",
    ".mp3", ".mp4", ".wav", ".ogg", ".mov", ".avi",
})

_SCAN_PROFILE_FILENAME = "scan_profile.yaml"
_DEFAULT_SCAN_PROFILE: dict = {
    "include_extensions": [
        ".py", ".ts", ".tsx", ".js", ".jsx", ".go", ".rs", ".java", ".kt",
        ".rb", ".md", ".rst", ".toml", ".yaml", ".yml", ".json", ".sql", ".sh",
    ],
    "exclude_dirs": [
        "node_modules", ".git", "venv", ".venv", "__pycache__",
        "dist", "build", ".mypy_cache", ".pytest_cache",
    ],
    "exclude_patterns": ["*.min.js", "*.min.css", "*.lock", "package-lock.json"],
    "max_files": 300,
}

_SCAN_PROFILE_YAML_HEADER = """\
# terminal-hub scan profile — controls which files are analyzed
# Generated by /th:gh-plan-analyze — edit freely

"""

_MD_SUFFIXES = {".md", ".rst", ".txt"}


def _is_markdown(path: str) -> bool:
    return Path(path).suffix.lower() in _MD_EXTENSIONS


def _scan_profile_path(root: Path) -> Path:
    return root / "hub_agents" / _SCAN_PROFILE_FILENAME


def _load_scan_profile(root: Path) -> dict:
    """Load hub_agents/scan_profile.yaml; fall back to defaults if absent or invalid."""
    try:
        import yaml as _yaml
        p = _scan_profile_path(root)
        if p.exists():
            data = _yaml.safe_load(p.read_text(encoding="utf-8")) or {}
            if isinstance(data, dict):
                merged = dict(_DEFAULT_SCAN_PROFILE)
                merged.update(data)
                return merged
    except Exception:
        pass
    return dict(_DEFAULT_SCAN_PROFILE)


def _scan_profile_default_yaml() -> str:
    """Return the default scan_profile.yaml content as a string."""
    import yaml as _yaml
    return _SCAN_PROFILE_YAML_HEADER + _yaml.dump(_DEFAULT_SCAN_PROFILE, default_flow_style=False)


def _extract_file_index(file_path: str, content: str) -> dict:
    """Extract a compact structural summary from a file's content."""
    suffix = Path(file_path).suffix.lower()

    if suffix == ".py":
        try:
            tree = ast.parse(content, filename=file_path)
        except (SyntaxError, ValueError):
            return {"path": file_path, "type": "python", "parse_error": True,
                    "lines": content.count("\n")}
        exports = [
            n.name for n in ast.walk(tree)
            if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
            and not n.name.startswith("_")
        ]
        imports = [
            node.names[0].name
            for node in ast.walk(tree) if isinstance(node, ast.Import)
        ][:5]
        return {
            "path": file_path,
            "type": "python",
            "exports": exports,
            "imports": imports,
            "module_doc": (ast.get_docstring(tree) or "")[:120],
            "lines": content.count("\n"),
        }

    if suffix in _MD_SUFFIXES:
        headings = [
            ln.lstrip("# ").strip()
            for ln in content.splitlines() if ln.startswith("#")
        ]
        return {
            "path": file_path,
            "type": "markdown",
            "headings": headings[:10],
            "first_200": content[:200],
        }

    return {"path": file_path, "type": "other", "lines": content.count("\n")}


def _file_hash_path(root: Path) -> Path:
    from extensions.gh_management.github_planner.project_docs import _gh_planner_docs_dir
    return _gh_planner_docs_dir(root) / "file_hashes.json"


def _load_file_hashes(root: Path) -> dict[str, str]:
    p = _file_hash_path(root)
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def _save_file_hashes(root: Path, hashes: dict[str, str]) -> None:
    p = _file_hash_path(root)
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(".tmp")
    tmp.write_text(json.dumps(hashes, indent=2), encoding="utf-8")
    os.replace(tmp, p)


def _file_tree_cache_path(root: Path) -> Path:
    from extensions.gh_management.github_planner.project_docs import _gh_planner_docs_dir
    return _gh_planner_docs_dir(root) / "file_tree.json"


def _should_ignore(name: str, extra_exclude_dirs: frozenset[str] | None = None) -> bool:
    """Return True if directory/file name matches an ignore pattern."""
    ignore_set = _FILE_TREE_IGNORE
    if extra_exclude_dirs:
        ignore_set = _FILE_TREE_IGNORE | extra_exclude_dirs
    if name in ignore_set:
        return True
    for pat in ignore_set:
        if pat.startswith("*") and name.endswith(pat[1:]):
            return True
    return False


def _build_file_tree(root: Path, extra_exclude_dirs: frozenset[str] | None = None) -> tuple[dict, list[str]]:
    """Walk root directory, return (nested_tree, flat_index) excluding ignored paths."""
    flat: list[str] = []

    def _walk(directory: Path, rel_prefix: str) -> dict:
        node: dict = {}
        try:
            entries = sorted(directory.iterdir(), key=lambda p: (p.is_file(), p.name.lower()))
        except PermissionError:
            return node
        for entry in entries:
            if _should_ignore(entry.name, extra_exclude_dirs):
                continue
            rel = f"{rel_prefix}{entry.name}"
            if entry.is_dir():
                children = _walk(entry, rel + "/")
                node[entry.name + "/"] = children
            else:
                node[entry.name] = {"size": entry.stat().st_size, "ext": entry.suffix.lower()}
                flat.append(rel)
        return node

    tree = _walk(root, "")
    return tree, flat


def _do_get_scan_profile_status() -> dict:
    """Check if scan_profile.yaml exists in hub_agents/. Return status + default content."""
    root = _pkg().get_workspace_root()
    p = _scan_profile_path(root)
    if p.exists():
        try:
            profile = _load_scan_profile(root)
            return {
                "exists": True,
                "path": str(p.relative_to(root)),
                "profile": profile,
                "_display": f"📋 scan_profile.yaml — {len(profile.get('include_extensions', []))} extensions, max {profile.get('max_files', 300)} files",
            }
        except Exception as exc:
            return {"exists": True, "error": str(exc), "_display": f"⚠️ scan_profile.yaml exists but could not be loaded: {exc}"}
    default_yaml = _scan_profile_default_yaml()
    return {
        "exists": False,
        "needs_creation": True,
        "default_content": default_yaml,
        "_display": (
            "📋 No scan_profile.yaml found.\n"
            "Create `hub_agents/scan_profile.yaml` to control which files are analyzed?\n"
            "*(yes / customize / skip)*"
        ),
    }


def _do_create_scan_profile(content: str | None = None) -> dict:
    """Write hub_agents/scan_profile.yaml (default or custom content)."""
    root = _pkg().get_workspace_root()
    p = _scan_profile_path(root)
    p.parent.mkdir(parents=True, exist_ok=True)
    text = content if content else _scan_profile_default_yaml()
    p.write_text(text, encoding="utf-8")
    return {
        "created": True,
        "path": str(p.relative_to(root)),
        "_display": f"✅ Created hub_agents/{_SCAN_PROFILE_FILENAME}",
    }


def _do_start_repo_analysis(repo: str | None = None) -> dict:
    _p = _pkg()

    resolved = _p._resolve_repo(repo)
    if not resolved:
        return {"error": "repo_required", "message": "Pass repo='owner/repo' or configure via setup_workspace.", "_hook": None}

    gh, err = _p._get_github_client()
    if gh is None:
        return {"error": "github_unavailable", "message": err, "_guidance": _p._G_AUTH}

    try:
        with gh:
            tree = gh.list_repo_tree()
    except Exception as exc:
        return {"error": "github_error", "message": str(exc), "_hook": None}

    tree = tree[:_MAX_ANALYSIS_FILES]
    md_files = [f for f in tree if _is_markdown(f["path"])]
    code_files = [f for f in tree if not _is_markdown(f["path"])]
    code_files.sort(key=lambda f: f["size"])

    _ANALYSIS_CACHE[resolved] = {
        "pending_md": md_files,
        "pending_code": code_files,
        "analyzed": [],
        "skipped": [],
        "repo": resolved,
        "started_at": time.time(),
        "last_fetched": None,
    }

    return {
        "repo": resolved,
        "total_files": len(tree),
        "md_count": len(md_files),
        "code_count": len(code_files),
        "status": "ready",
        "_display": f"✓ Analysis started — {resolved} ({len(tree)} files: {len(md_files)} docs, {len(code_files)} code)",
    }


def _do_fetch_analysis_batch(repo: str | None = None, batch_size: int = ANALYSIS_BATCH_SIZE) -> dict:
    _p = _pkg()

    resolved = _p._resolve_repo(repo)
    if not resolved or resolved not in _ANALYSIS_CACHE:
        return {"error": "analysis_not_started", "message": "Call start_repo_analysis first.", "_hook": None}

    state = _ANALYSIS_CACHE[resolved]
    batch_size = max(ANALYSIS_BATCH_SIZE_MIN, min(batch_size, ANALYSIS_BATCH_SIZE_MAX))

    gh, err = _p._get_github_client()
    if gh is None:
        return {"error": "github_unavailable", "message": err, "_guidance": _p._G_AUTH}

    queue = state["pending_md"] if state["pending_md"] else state["pending_code"]
    to_fetch = queue[:batch_size]

    files_out: list[dict] = []
    with gh:
        for file_meta in to_fetch:
            path = file_meta["path"]
            is_md = _is_markdown(path)
            try:
                content = gh.get_file_content(path)
                files_out.append({"path": path, "content": content, "is_markdown": is_md})
                state["analyzed"].append({"path": path, "is_markdown": is_md})
            except Exception as exc:
                from extensions.gh_management.github_planner.client import GitHubError
                reason = getattr(exc, "error_code", "unknown")
                state["skipped"].append({"path": path, "reason": reason})

            if is_md and file_meta in state["pending_md"]:
                state["pending_md"].remove(file_meta)
            elif file_meta in state["pending_code"]:
                state["pending_code"].remove(file_meta)

    state["last_fetched"] = time.time()
    remaining = len(state["pending_md"]) + len(state["pending_code"])
    done = remaining == 0

    return {
        "repo": resolved,
        "files": files_out,
        "analyzed_count": len(state["analyzed"]),
        "remaining_count": remaining,
        "done": done,
    }


def _do_get_analysis_status(repo: str | None = None) -> dict:
    resolved = _pkg()._resolve_repo(repo)
    if not resolved or resolved not in _ANALYSIS_CACHE:
        return {"error": "analysis_not_started", "message": "Call start_repo_analysis first.", "_hook": None}

    state = _ANALYSIS_CACHE[resolved]
    remaining = len(state["pending_md"]) + len(state["pending_code"])
    return {
        "repo": resolved,
        "analyzed_count": len(state["analyzed"]),
        "remaining_count": remaining,
        "skipped_count": len(state["skipped"]),
        "analyzed_paths": [f["path"] for f in state["analyzed"]],
        "remaining_paths": [f["path"] for f in state["pending_md"] + state["pending_code"]],
        "done": remaining == 0,
    }


def _do_get_file_tree(refresh: bool = False) -> dict:
    """Return a cached file-tree index of the workspace root."""
    from datetime import datetime, timezone

    root = _pkg().get_workspace_root()
    cache_path = _file_tree_cache_path(root)

    if not refresh and _FILE_TREE_CACHE:
        fetched_at_str = _FILE_TREE_CACHE.get("fetched_at", "")
        try:
            fetched_at = datetime.fromisoformat(fetched_at_str)
            age = (datetime.now(timezone.utc) - fetched_at).total_seconds()
            if age < _FILE_TREE_TTL:
                return dict(_FILE_TREE_CACHE)
        except (ValueError, TypeError):
            pass

    if not refresh and cache_path.exists():
        try:
            cached = json.loads(cache_path.read_text(encoding="utf-8"))
            fetched_at = datetime.fromisoformat(cached["fetched_at"])
            age = (datetime.now(timezone.utc) - fetched_at).total_seconds()
            if age < _FILE_TREE_TTL:
                _FILE_TREE_CACHE.clear()
                _FILE_TREE_CACHE.update(cached)
                return dict(cached)
        except (OSError, json.JSONDecodeError, KeyError, ValueError):
            pass

    profile = _load_scan_profile(root)
    profile_exclude = frozenset(profile.get("exclude_dirs", []))
    tree, flat_index = _build_file_tree(root, extra_exclude_dirs=profile_exclude)
    now = datetime.now(timezone.utc).isoformat()
    result = {
        "fetched_at": now,
        "root": str(root),
        "tree": tree,
        "flat_index": flat_index,
        "total_files": len(flat_index),
        "_display": f"✓ File tree built — {len(flat_index)} files in {root.name}",
    }

    cache_path.parent.mkdir(parents=True, exist_ok=True)
    tmp = cache_path.with_suffix(".tmp")
    tmp.write_text(json.dumps(result, indent=2), encoding="utf-8")
    os.replace(tmp, cache_path)

    _FILE_TREE_CACHE.clear()
    _FILE_TREE_CACHE.update(result)
    return result


def _do_analyze_repo_full(repo: str | None = None) -> dict:
    """Fetch the full repo tree, extract structured file index, return in one call."""
    _p = _pkg()

    resolved = _p._resolve_repo(repo)
    if not resolved:
        return {"error": "repo_required",
                "message": "Pass repo='owner/repo' or configure via setup_workspace.",
                "_hook": None}

    gh, err = _p._get_github_client()
    if gh is None:
        return {"error": "github_unavailable", "message": err, "_guidance": _p._G_AUTH}

    root = _p.get_workspace_root()
    stored_hashes = _load_file_hashes(root)
    profile = _load_scan_profile(root)
    _include_exts = frozenset(profile.get("include_extensions", []))
    _exclude_dirs = frozenset(profile.get("exclude_dirs", []))
    _max_files = profile.get("max_files", _MAX_ANALYSIS_FILES)

    import fnmatch as _fnmatch
    _exclude_patterns = profile.get("exclude_patterns", [])

    def _profile_allows(path: str) -> bool:
        p = Path(path)
        for part in p.parts[:-1]:
            if part in _exclude_dirs:
                return False
        name = p.name
        if any(_fnmatch.fnmatch(name, pat) for pat in _exclude_patterns):
            return False
        if _include_exts:
            return p.suffix.lower() in _include_exts
        return p.suffix.lower() not in _BINARY_EXTENSIONS

    try:
        with gh:
            tree = gh.list_repo_tree()
    except Exception as exc:
        return {"error": "github_error", "message": str(exc), "_hook": None}

    raw_tree_len = len(tree)
    tree = tree[:_max_files]
    omitted_files = max(0, raw_tree_len - len(tree))

    new_hashes: dict[str, str] = {}
    to_fetch = []
    skipped_unchanged = 0

    for f in tree:
        path = f["path"]
        if not _profile_allows(path):
            skipped_unchanged += 1
            continue
        tree_sha = f.get("sha", "")
        if tree_sha and stored_hashes.get(path) == tree_sha:
            skipped_unchanged += 1
            new_hashes[path] = tree_sha
        else:
            to_fetch.append(f)

    file_index = []
    skipped_errors = []

    if to_fetch:
        with gh:
            for f in to_fetch:
                path = f["path"]
                try:
                    content = gh.get_file_content(path)
                    entry = _extract_file_index(path, content)
                    file_index.append(entry)
                    sha = f.get("sha") or hashlib.sha256(content.encode()).hexdigest()[:32]
                    new_hashes[path] = sha
                except Exception as exc:
                    reason = getattr(exc, "error_code", "unknown")
                    skipped_errors.append({"path": path, "reason": reason})

    _save_file_hashes(root, new_hashes)

    _FILE_TREE_CACHE.clear()

    _ANALYSIS_CACHE[resolved] = {
        "pending_md": [], "pending_code": [],
        "analyzed": [{"path": e["path"], "is_markdown": e["type"] == "markdown"}
                     for e in file_index],
        "skipped": skipped_errors,
        "repo": resolved,
        "started_at": time.time(),
        "last_fetched": time.time(),
    }

    cap_warning = (
        f"\n  ⚠ {omitted_files} files omitted (repo exceeds {_max_files}-file cap)"
        if omitted_files > 0 else ""
    )
    return {
        "repo": resolved,
        "file_index": file_index,
        "total_files": len(tree),
        "fetched": len(file_index),
        "skipped_unchanged": skipped_unchanged,
        "skipped_errors": len(skipped_errors),
        "omitted_files": omitted_files,
        "_display": (
            f"✓ Repo analyzed — {resolved}\n"
            f"  Files fetched : {len(file_index)} "
            f"({skipped_unchanged} unchanged, {len(skipped_errors)} skipped)"
            f"{cap_warning}"
        ),
    }


def _do_run_analyzer() -> dict:
    from extensions.gh_management.github_planner.analyzer import (
        process_snapshot, write_snapshot, summarize_for_prompt, snapshot_age_hours, load_snapshot
    )
    from extensions.gh_management.github_planner.labels import _LABEL_CACHE, _normalise_labels
    _p = _pkg()

    root = _p.get_workspace_root()
    if err := _p.ensure_initialized(root):
        return err

    gh, error_message = _p._get_github_client()
    if gh is None:
        return {"error": "github_unavailable", "message": error_message, "_guidance": _p._G_AUTH}

    env = _p.read_env(root)
    repo = env.get("GITHUB_REPO", "unknown")

    with gh:
        try:
            issues = gh.list_issues(state="all", per_page=50)
            labels = gh.list_labels()
            members = gh.list_collaborators()
        except Exception as exc:
            return {"error": "github_error", "message": str(exc)}

    from extensions.gh_management.github_planner.labels import _normalise_labels
    if repo not in _LABEL_CACHE:
        _LABEL_CACHE[repo] = _normalise_labels(labels)

    snapshot = process_snapshot(issues, labels, members, repo=repo)
    path = write_snapshot(root, snapshot)
    summary = summarize_for_prompt(snapshot)

    n_issues = snapshot["issues"]["total_sampled"]
    n_open = snapshot["issues"]["total_open"]
    n_labels = len(snapshot["labels"])
    n_members = len(snapshot["members"])
    member_names = ", ".join(m["login"] for m in snapshot["members"][:3])

    display = (
        f"✓ Analyzer complete — {repo}\n"
        f"  Issues sampled : {n_issues} ({n_open} open)\n"
        f"  Labels found   : {n_labels}\n"
        f"  Team members   : {n_members}"
        + (f" ({member_names})" if member_names else "") + "\n"
        f"  Snapshot saved : hub_agents/analyzer_snapshot.json"
    )
    if summary:
        display += f"\n\n  {summary}"

    return {
        "snapshot_file": str(path.relative_to(root)),
        "summary": summary,
        "_display": display,
    }
